### ISSUE TITLE
Problems about installing torch_tvm ?

### ISSUE THREAD

**Issue by ybai62868** [pytorch/tvm#153]
Hi,
when I clone this repo to my local folder and I use 'python setup.py install'. It has the following errors:

running install
running build
running build_py
copying torch_tvm/version.py -> build/lib.macosx-10.9-x86_64-3.7/torch_tvm
running egg_info
writing torch_tvm.egg-info/PKG-INFO
writing dependency_links to torch_tvm.egg-info/dependency_links.txt
writing top-level names to torch_tvm.egg-info/top_level.txt
reading manifest file 'torch_tvm.egg-info/SOURCES.txt'
writing manifest file 'torch_tvm.egg-info/SOURCES.txt'
running build_ext
running cmake_build
make: *** No targets specified and no makefile found.  Stop.
Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    url='https://github.com/pytorch/tvm',
  File "/Users/baiyang/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 203, in run
    setuptools.command.install.install.run(self)
  File "/Users/baiyang/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 65, in run
    orig.install.run(self)
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 187, in run
    self.run_command('cmake_build')
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/baiyang/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 176, in run
    self._run_build()
  File "setup.py", line 165, in _run_build
    subprocess.check_call(build_args)
  File "/Users/baiyang/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '12']' returned non-zero exit status 2.
---
Can you help me to solve this problem? Thanks a lot.

**Comment by ybai62868** [comment]
BTW, where should I put this repo in my machine?

**Comment by bwasti** [comment]
Have you done a recursive clone?

**Comment by taeyeoneric1** [comment]
> 您是否进行了递归克隆？
how to do a recursive clone?
