### ISSUE TITLE
Cannot Import torch_tvm

### ISSUE THREAD

**Issue by scnakandala** [pytorch/tvm#93]
I have installed the torch nightly build (torch-1.3.0.dev20190819-cp36-cp36m-linux_x86_64.whl) and successfully build torch_tvm.

However, when I try to import torch_tvm I get the following error:

```
>>> import torch_tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hummingbird/.local/lib/python3.6/site-packages/torch_tvm/__init__.py", line 9, in <module>
    from ._torch_tvm import *
ImportError: /home/hummingbird/.local/lib/python3.6/site-packages/torch_tvm/_torch_tvm.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5torch3jit16SubgraphRewriter22RegisterRewritePatternERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_
```

Do I need to add anything to the library path?

**Comment by bwasti** [comment]
this seems similar to issue #77 - please try this fix:
https://github.com/pytorch/tvm/issues/77#issuecomment-519614588

**Comment by un-knight** [comment]
@scnakandala Hi! Did you fix the problem? I got the same error.
